
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SachOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GiaoHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GiaoHang()
    {

        this.DonHangs = new HashSet<DonHang>();

    }


    public int MaGiaoHang { get; set; }

    public string TenNguoiNhan { get; set; }

    public string DiaChi { get; set; }

    public string SDT { get; set; }

    public string Email { get; set; }

    public Nullable<int> QuaTang { get; set; }

    public string LoiNhan { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DonHang> DonHangs { get; set; }

}

}
