
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SachOnline.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {

            this.DonHangs = new HashSet<DonHang>();

        }

        [Display(Name = "Mã Khách Hàng:")]
        public int MaKH { get; set; }
        [Display(Name = "Họ Tên:")]
        public string HoTen { get; set; }
        [Display(Name = "Tên Tài Khoản:")]
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật Khẩu:")]
        public string MaKhau { get; set; }
        [Display(Name = "Email:")]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ:")]
        public string DiaChi { get; set; }
        [Display(Name = "Điện Thoại:")]
        public string DienThoai { get; set; }
        [Display(Name = "Giới Tính:")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày Sinh:")]
        public Nullable<System.DateTime> NgaySinh { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<DonHang> DonHangs { get; set; }

    }

}
